### PR TITLE
travis: add release build

### LINKED ISSUE #92: Add release builds to CI
We should build release and debug in CI.

Related to #91.

### PR DESCRIPTION
**Pull request by julianoes**
Run release builds in travis and fix compile errors for release builds.

Closes #92.

### CODE REVIEW

**Comment by julianoes** [comment]
Note to self: I give up. Need to debug this on a Windows machine.

**Comment by darioxz** [comment]
Is this ready to get reviewed?

**Comment by julianoes** [comment]
> Is this ready to get reviewed?

Yes please.

**Comment by mrpollo** [comment]
@julianoes can you update your branch?, I'll make sure to merge!

**Pull request merged**
