### PR TITLE
info: add vendor and product ID and name

### PR DESCRIPTION
**Pull request by julianoes**
This adds the vendor and product ID and name back.

### CODE REVIEW

**Comment by julianoes** [comment]
I guess it could also live in the same struct, you're right. But version is misleading for a vendor and product name.

**Comment by julianoes** [comment]
I'll merge this for now, we can always change it.

**Comment by hamishwillee** [comment]
One bugger about this develop codeline approach is that it isn't clear when the changes are available in mainline/release - so nothing to trigger me to regenerate our API ref.

**Comment by julianoes** [comment]
I vote to get rid of develop and work on master and have releases of master.

**Comment by hamishwillee** [comment]
Me too. @mrpollo any objections to getting rid of develop and using releases of master? We can always create a release branch off master or just create a tag. If we find that managing development gets tough we can always add it back in again.

**Pull request merged**
