### PR TITLE
core: make Info printfs blue

### PR DESCRIPTION
**Pull request by julianoes**
In order to distinguish Info and Debug, Info is now made blue.

Also, the color is now properly set at the beginning of the line instead
of after the time.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Code-wise this is fine, but what is the semantic difference between info and debug? ie when would you use one and not the other?

The most common output should be white I'd think?

**Comment by julianoes** [comment]
> Code-wise this is fine, but what is the semantic difference between info and debug? ie when would you use one and not the other?
> 
> The most common output should be white I'd think?

Ok, so you would vote to have debug output blue? I tried grey but that was not really visible in my console.

**Comment by mrpollo** [comment]
I agree with @darioxz we should only have the `[Time | Debug]` part in color.

I like the blue!
https://media.giphy.com/media/tRx1Zf2jF2N8I/giphy.gif

**Comment by julianoes** [comment]
Ok, changed in b21c983.

**Comment by mrpollo** [comment]
@julianoes Can you please rebase master and then make rebase/merge back ? this is now approved 👍

**Pull request merged**
