### PR TITLE
gRPC follow up fixes

### PR DESCRIPTION
**Pull request by julianoes**
These are follow up fixes after #143 and 173.

Currently, the Python client does not work for me:

```
./grpc/python_client/sync_client.py
Traceback (most recent call last):
  File "./grpc/python_client/sync_client.py", line 9, in <module>
    import action_pb2_grpc
ImportError: No module named action_pb2_grpc
```

### CODE REVIEW

**Comment by julianoes** [comment]
The Python imports are resolved, now the Python clients need updating:
```
root@31c392c9a29d:/home/docker1000/src/DroneCore# python3 ./grpc/python_client/sync_client.py
Traceback (most recent call last):
  File "./grpc/python_client/sync_client.py", line 41, in <module>
    run()
  File "./grpc/python_client/sync_client.py", line 18, in run
    if arm_result.result == dc.ActionResult.SUCCESS:
AttributeError: module 'dronecore_pb2' has no attribute 'ActionResult'
root@31c392c9a29d:/home/docker1000/src/DroneCore# python3 ./grpc/python_client/async_client.py 
Traceback (most recent call last):
  File "./grpc/python_client/async_client.py", line 79, in <module>
    run()
  File "./grpc/python_client/async_client.py", line 51, in run
    arm_result = stub.Arm.future(dc.Empty())
AttributeError: 'DroneCoreRPCStub' object has no attribute 'Arm'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./grpc/python_client/async_client.py", line 29, in print_altitude
    dc_telemetry.TelemetryEmpty())):
AttributeError: module 'telemetry_pb2' has no attribute 'TelemetryEmpty'

root@31c392c9a29d:/home/docker1000/src/DroneCore# python3 ./grpc/python_client/fly_mission.py  
Traceback (most recent call last):
  File "./grpc/python_client/fly_mission.py", line 112, in <module>
    run()
  File "./grpc/python_client/fly_mission.py", line 36, in run
    mission_items.append(dc.MissionItem(
AttributeError: module 'dronecore_pb2' has no attribute 'MissionItem'
```

**Comment by julianoes** [comment]
Ok, and the Python examples work again.

**Comment by julianoes** [comment]
I had ignored #174. This is now rebased.

**Comment by JonasVautherin** [comment]
Tested all three clients (`sync_client.py`, `async_client.py`, `fly_mission.py`), and it works for me 👍.

**Pull request merged**
