### PR TITLE
Serial connection support for macOS

### PR DESCRIPTION
**Pull request by julianoes**
It recently came up on Slack that it would be good to have support for the serial connection on macOS.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@julianoes This concerns me - I was not aware that any of our APIs were "platform specific". If we don't support an API on a particular platform then that should be part of the documentation.

So does this work on Windows? Are there any other APIs that we know only work on Linux, Windows or Mac?

**Comment by JonasVautherin** [comment]
@hamishwillee: For what I understand from the code, the serial connection is now supported on Linux and macOS, and not on Windows.

**Comment by hamishwillee** [comment]
> @hamishwillee: For what I understand from the code, the serial connection is now supported on Linux and macOS, and not on Windows.

Thanks. Then we should probably add a warning to `DroneCore::add_any_connection()` and `add_serial_connection()` docs. Something like

> @warning This method is not supported on Windows (it is supported on Linux and macOS).

I am making the assumption that everything else works everywhere.

**Comment by JonasVautherin** [comment]
> I am making the assumption that everything else works everywhere.

I wouldn't know :grinning:.

**Comment by julianoes** [comment]
@hamishwillee you're right.
Let's add that comment about Windows.

UDP and TCP connections are supported on all 3 operating systems.

**Pull request merged**
